#
# SPDX-FileCopyrightText: 2021 Alexis Lopez Zubieta <contact@azubieta.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Continuous AppImage build 

on:
  push

jobs:
  build-appimage:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtdeclarative5-dev gettext build-essential extra-cmake-modules \
            kirigami2-dev mpv libmpv-dev libkf5xmlgui-dev qtquickcontrols2-5-dev libkf5kio-dev libkf5iconthemes-dev \
            libkf5filemetadata-dev libkf5config-dev breeze-dev qtquickcontrols2-5-dev cmake g++
      - name: configure
        run: cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      - name: build
        run: make -j`nproc`  install DESTDIR=AppDir
      - name: Resolve package version
        id: resolve_version
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          GIT_BRACH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]+/-/g')
          echo "HARUNA_VERSION=${GIT_BRACH}-${GIT_HASH}" >> $GITHUB_ENV
      - name: pack
        uses: docker://appimagecrafters/appimage-builder:0.8.4
        with:
          entrypoint: appimage-builder
          args: --recipe ./appimage-amd64.yaml --skip-test
          
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
